"""Locate the bundled HTML documentation at runtime.

The HTML docs are generated by ``tools/build_docs.py`` into ``docs/html`` and
shipped with the application (see ``ChapterForge.spec``). This module resolves
that directory whether running from source or from a PyInstaller build, and
opens a page in the user's default browser.
"""

from __future__ import annotations

import os
import sys

# Generated page filenames (see tools/build_docs.py PAGES).
HOME = "index.html"
USER_GUIDE = "USER_GUIDE.html"
DEPLOYMENT = "DEPLOYMENT.html"
CHANGELOG = "CHANGELOG.html"
THIRD_PARTY = "THIRD_PARTY.html"


def _candidate_dirs() -> list:
    dirs = []
    if getattr(sys, "frozen", False):
        exe_dir = os.path.dirname(sys.executable)
        dirs += [os.path.join(exe_dir, "docs", "html")]
        meipass = getattr(sys, "_MEIPASS", None)
        if meipass:
            dirs += [os.path.join(meipass, "docs", "html")]
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(here)
    dirs += [
        os.path.join(repo_root, "docs", "html"),
        os.path.join(here, "docs", "html"),
    ]
    return dirs


def docs_dir() -> str | None:
    """Return the directory containing the generated HTML docs, or None."""
    for d in _candidate_dirs():
        if os.path.isfile(os.path.join(d, HOME)):
            return d
    return None


def doc_path(page: str = HOME) -> str | None:
    """Return the absolute path to a generated doc page, or None if missing."""
    d = docs_dir()
    if not d:
        return None
    candidate = os.path.join(d, page)
    return candidate if os.path.isfile(candidate) else None


def open_doc(page: str = HOME) -> bool:
    """Open a documentation page in the default browser.

    Tries to open local HTML files first (development), then falls back to
    GitHub Pages online documentation. Returns True if a page was opened.
    """
    import webbrowser

    # Try local files first (for development)
    path = doc_path(page)
    if path:
        try:
            webbrowser.open("file:///" + path.replace("\\", "/"))
            return True
        except Exception:
            pass

    # Fall back to GitHub Pages
    try:
        url = f"https://bits-acb.github.io/chapterforge/html/{page}"
        webbrowser.open(url)
        return True
    except Exception:
        return False
